name: Pull sur le VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_SSH_HOST }}
          VPS_USER: ${{ secrets.VPS_SSH_NAME }}
          VPS_DEPLOY_PATH: ${{ secrets.VPS_SSH_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd $VPS_DEPLOY_PATH && git pull"
          rm /tmp/ssh_key
